// [CL-TOP100-DESTINATIONS-20260325] 대한민국 신혼부부 인기 Top 100 여행지
import type { Destination } from './honeymoon-destinations';

export const DESTINATIONS: Destination[] = [
  // ─────────────────────────────────────────────────────
  // 1. 몰디브 (기존)
  // ─────────────────────────────────────────────────────
  {
    id: 'maldives',
    name: '몰디브',
    nameEn: 'Maldives',
    region: '남아시아/인도양',
    coordinates: [73.5, 3.2],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['풀빌라', '올인클루시브', '리조트'],
    budgetRange: { min: 8_000_000, max: 15_000_000 },
    nights: 7,
    features: ['수상 빌라', '프라이빗 비치', '스노클링', '선셋 크루즈'],
    bestBookingWeeks: 12,
    visaRequired: false,
    description: '인도양 한가운데 떠 있는 수상 빌라에서 둘만의 시간을 보내세요.',
    markerEmoji: '🏝️',
    highlights: ['수상 빌라 숙박', '산호초 스노클링', '프라이빗 디너'],
    costBreakdown: {
      flight: { min: 1_500_000, max: 3_000_000 },
      accommodation: { min: 4_500_000, max: 9_000_000 },
      local: { min: 2_000_000, max: 3_000_000 },
    },
  },
  // ─────────────────────────────────────────────────────
  // 2. 유럽 (기존)
  // ─────────────────────────────────────────────────────
  {
    id: 'europe',
    name: '유럽',
    nameEn: 'Europe',
    region: '유럽',
    coordinates: [2.35, 48.86],
    concepts: ['관광', '쇼핑'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 6_000_000, max: 12_000_000 },
    nights: 10,
    features: ['다국가 여행', '미술관 투어', '와인 & 다이닝', '역사 유적'],
    bestBookingWeeks: 16,
    visaRequired: false,
    description: '파리에서 로마까지, 유럽의 로맨틱한 도시들을 한 번에 누비세요.',
    markerEmoji: '🗼',
    highlights: ['에펠탑 야경', '베네치아 곤돌라', '바르셀로나 가우디 건축'],
    costBreakdown: {
      flight: { min: 1_500_000, max: 2_500_000 },
      accommodation: { min: 2_500_000, max: 5_500_000 },
      local: { min: 2_000_000, max: 4_000_000 },
    },
  },
  // ─────────────────────────────────────────────────────
  // 3. 하와이 (기존)
  // ─────────────────────────────────────────────────────
  {
    id: 'hawaii',
    name: '하와이',
    nameEn: 'Hawaii',
    region: '북미',
    coordinates: [-155.5, 19.9],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['리조트', '호텔'],
    budgetRange: { min: 7_000_000, max: 13_000_000 },
    nights: 7,
    features: ['와이키키 비치', '화산 국립공원', '스노클링', '루아우 쇼'],
    bestBookingWeeks: 12,
    visaRequired: true,
    description: '태평양 한가운데 열대 낙원에서 액티비티와 휴양을 동시에 즐기세요.',
    markerEmoji: '🌺',
    highlights: ['와이키키 서핑', '하와이 화산 트레킹', '전통 루아우 디너'],
    costBreakdown: {
      flight: { min: 2_000_000, max: 3_500_000 },
      accommodation: { min: 3_000_000, max: 6_000_000 },
      local: { min: 2_000_000, max: 3_500_000 },
    },
  },
  // ─────────────────────────────────────────────────────
  // 4. 발리 (기존)
  // ─────────────────────────────────────────────────────
  {
    id: 'bali',
    name: '발리',
    nameEn: 'Bali',
    region: '동남아',
    coordinates: [115.2, -8.65],
    concepts: ['휴양', '관광', '액티비티'],
    accommodationTypes: ['풀빌라', '리조트', '에어비앤비'],
    budgetRange: { min: 3_500_000, max: 7_000_000 },
    nights: 7,
    features: ['라이스 테라스', '울루와뚜 절벽', '스파 & 요가', '서핑'],
    bestBookingWeeks: 8,
    visaRequired: false,
    description: '열대 자연과 힌두 문화가 어우러진 발리에서 감성 허니문을 즐기세요.',
    markerEmoji: '🌴',
    highlights: ['우붓 라이스 테라스', '누사페니다 스노클링', '발리 스파 체험'],
    costBreakdown: {
      flight: { min: 800_000, max: 1_500_000 },
      accommodation: { min: 1_500_000, max: 3_500_000 },
      local: { min: 1_200_000, max: 2_000_000 },
    },
  },
  // ─────────────────────────────────────────────────────
  // 5. 칸쿤 (기존)
  // ─────────────────────────────────────────────────────
  {
    id: 'cancun',
    name: '칸쿤',
    nameEn: 'Cancun',
    region: '중남미/카리브',
    coordinates: [-86.85, 21.16],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['올인클루시브', '리조트'],
    budgetRange: { min: 7_000_000, max: 14_000_000 },
    nights: 7,
    features: ['올인클루시브 리조트', '세노테 다이빙', '치첸이트사', '카리브해 비치'],
    bestBookingWeeks: 14,
    visaRequired: false,
    description: '카리브해 에메랄드빛 바다와 마야 유적이 기다리는 칸쿤으로 떠나세요.',
    markerEmoji: '🏖️',
    highlights: ['세노테 스노클링', '치첸이트사 유적 관광', '카리브해 선셋 크루즈'],
    costBreakdown: {
      flight: { min: 2_500_000, max: 4_000_000 },
      accommodation: { min: 3_000_000, max: 7_000_000 },
      local: { min: 1_500_000, max: 3_000_000 },
    },
  },
  // ─────────────────────────────────────────────────────
  // 6. 제주 (기존)
  // ─────────────────────────────────────────────────────
  {
    id: 'jeju',
    name: '제주',
    nameEn: 'Jeju',
    region: '국내',
    coordinates: [126.57, 33.45],
    concepts: ['휴양', '관광', '액티비티'],
    accommodationTypes: ['리조트', '호텔', '에어비앤비'],
    budgetRange: { min: 1_500_000, max: 4_000_000 },
    nights: 4,
    features: ['올레길 트레킹', '해안 드라이브', '흑돼지 맛집', '성산일출봉'],
    bestBookingWeeks: 4,
    visaRequired: false,
    description: '국내에서 가장 로맨틱한 섬, 제주에서 편안한 신혼여행을 시작하세요.',
    markerEmoji: '🍊',
    highlights: ['성산일출봉 일출', '협재 해수욕장', '제주 흑돼지 맛집 투어'],
    costBreakdown: {
      flight: { min: 200_000, max: 400_000 },
      accommodation: { min: 800_000, max: 2_200_000 },
      local: { min: 500_000, max: 1_400_000 },
    },
  },

  // ═══════════════════════════════════════════════════════
  // 동남아 (23 total — bali 위에 이미 포함, 나머지 22)
  // ═══════════════════════════════════════════════════════
  {
    id: 'phuket',
    name: '푸켓',
    nameEn: 'Phuket',
    region: '동남아',
    coordinates: [98.34, 7.88],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['풀빌라', '리조트', '호텔'],
    budgetRange: { min: 3_000_000, max: 6_500_000 },
    nights: 6,
    features: ['피피섬 투어', '파통 비치', '타이 마사지', '야시장'],
    bestBookingWeeks: 8,
    visaRequired: false,
    description: '안다만 해의 에메랄드빛 바다와 석회암 절벽이 매력적인 태국 대표 휴양지입니다.',
    markerEmoji: '⛱️',
    highlights: ['피피섬 스노클링', '팡아만 카약', '올드타운 야시장'],
    costBreakdown: {
      flight: { min: 600_000, max: 1_200_000 },
      accommodation: { min: 1_400_000, max: 3_300_000 },
      local: { min: 1_000_000, max: 2_000_000 },
    },
  },
  {
    id: 'danang',
    name: '다낭',
    nameEn: 'Da Nang',
    region: '동남아',
    coordinates: [108.22, 16.05],
    concepts: ['휴양', '관광', '쇼핑'],
    accommodationTypes: ['리조트', '호텔', '에어비앤비'],
    budgetRange: { min: 2_500_000, max: 5_000_000 },
    nights: 5,
    features: ['미케비치', '바나힐', '호이안 올드타운', '해산물 맛집'],
    bestBookingWeeks: 6,
    visaRequired: false,
    description: '가성비 최고의 베트남 해변 도시에서 휴양과 관광을 동시에 즐기세요.',
    markerEmoji: '🐉',
    highlights: ['바나힐 골든브릿지', '호이안 등불 축제', '미케비치 일출'],
    costBreakdown: {
      flight: { min: 500_000, max: 900_000 },
      accommodation: { min: 1_000_000, max: 2_500_000 },
      local: { min: 1_000_000, max: 1_600_000 },
    },
  },
  {
    id: 'boracay',
    name: '보라카이',
    nameEn: 'Boracay',
    region: '동남아',
    coordinates: [121.97, 11.97],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['리조트', '호텔'],
    budgetRange: { min: 3_000_000, max: 6_000_000 },
    nights: 5,
    features: ['화이트비치', '선셋 세일링', '호핑투어', '디몰 쇼핑'],
    bestBookingWeeks: 8,
    visaRequired: false,
    description: '세계에서 가장 아름다운 화이트 비치에서 로맨틱한 선셋을 감상하세요.',
    markerEmoji: '🏖️',
    highlights: ['화이트비치 선셋', '아일랜드 호핑투어', '패러세일링'],
    costBreakdown: {
      flight: { min: 600_000, max: 1_200_000 },
      accommodation: { min: 1_400_000, max: 3_000_000 },
      local: { min: 1_000_000, max: 1_800_000 },
    },
  },
  {
    id: 'cebu',
    name: '세부',
    nameEn: 'Cebu',
    region: '동남아',
    coordinates: [123.9, 10.31],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['리조트', '호텔'],
    budgetRange: { min: 2_500_000, max: 5_500_000 },
    nights: 5,
    features: ['오슬롭 고래상어', '카와산 폭포', '모알보알 스노클링', '막탄 리조트'],
    bestBookingWeeks: 6,
    visaRequired: false,
    description: '고래상어와 함께 수영하고 청록빛 폭포에서 캐녀닝을 즐기세요.',
    markerEmoji: '🐋',
    highlights: ['오슬롭 고래상어 투어', '카와산 캐녀닝', '모알보알 정어리떼 스노클링'],
    costBreakdown: {
      flight: { min: 500_000, max: 1_000_000 },
      accommodation: { min: 1_000_000, max: 2_800_000 },
      local: { min: 1_000_000, max: 1_700_000 },
    },
  },
  {
    id: 'koh-samui',
    name: '코사무이',
    nameEn: 'Koh Samui',
    region: '동남아',
    coordinates: [100.0, 9.51],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['풀빌라', '리조트'],
    budgetRange: { min: 3_500_000, max: 7_000_000 },
    nights: 6,
    features: ['앙통 국립공원', '프라이빗 풀빌라', '코팡안 풀문파티', '스파'],
    bestBookingWeeks: 8,
    visaRequired: false,
    description: '태국 만의 보석 같은 섬에서 프라이빗 풀빌라 허니문을 즐기세요.',
    markerEmoji: '🌊',
    highlights: ['앙통 국립공원 카약', '풀빌라 프라이빗 디너', '왓 쁠라이 랭 사원'],
    costBreakdown: {
      flight: { min: 700_000, max: 1_300_000 },
      accommodation: { min: 1_800_000, max: 3_700_000 },
      local: { min: 1_000_000, max: 2_000_000 },
    },
  },
  {
    id: 'singapore',
    name: '싱가포르',
    nameEn: 'Singapore',
    region: '동남아',
    coordinates: [103.85, 1.29],
    concepts: ['관광', '쇼핑'],
    accommodationTypes: ['호텔', '리조트'],
    budgetRange: { min: 3_000_000, max: 6_000_000 },
    nights: 4,
    features: ['마리나베이샌즈', '가든스바이더베이', '센토사', '차이나타운'],
    bestBookingWeeks: 6,
    visaRequired: false,
    description: '도시의 화려함과 다문화의 매력이 공존하는 가든시티를 만나세요.',
    markerEmoji: '🦁',
    highlights: ['마리나베이샌즈 인피니티풀', '가든스바이더베이 야경', '호커센터 미식 투어'],
    costBreakdown: {
      flight: { min: 500_000, max: 900_000 },
      accommodation: { min: 1_500_000, max: 3_500_000 },
      local: { min: 1_000_000, max: 1_600_000 },
    },
  },
  {
    id: 'bangkok',
    name: '방콕',
    nameEn: 'Bangkok',
    region: '동남아',
    coordinates: [100.5, 13.76],
    concepts: ['관광', '쇼핑', '액티비티'],
    accommodationTypes: ['호텔', '리조트'],
    budgetRange: { min: 2_500_000, max: 5_000_000 },
    nights: 5,
    features: ['왓포 사원', '짜뚜짝 시장', '루프탑 바', '수상시장'],
    bestBookingWeeks: 6,
    visaRequired: false,
    description: '황금빛 사원과 세계적인 스트릿푸드의 도시에서 활기찬 허니문을 즐기세요.',
    markerEmoji: '🛕',
    highlights: ['왕궁 & 왓포 사원 투어', '짜뚜짝 시장 쇼핑', '루프탑 바 선셋 칵테일'],
    costBreakdown: {
      flight: { min: 500_000, max: 800_000 },
      accommodation: { min: 1_000_000, max: 2_500_000 },
      local: { min: 1_000_000, max: 1_700_000 },
    },
  },
  {
    id: 'chiang-mai',
    name: '치앙마이',
    nameEn: 'Chiang Mai',
    region: '동남아',
    coordinates: [98.98, 18.79],
    concepts: ['관광', '액티비티'],
    accommodationTypes: ['리조트', '에어비앤비'],
    budgetRange: { min: 2_500_000, max: 5_000_000 },
    nights: 5,
    features: ['코끼리 생츄어리', '올드시티 사원', '야시장', '쿠킹 클래스'],
    bestBookingWeeks: 6,
    visaRequired: false,
    description: '태국 북부의 문화 수도에서 사원과 자연 속 힐링 허니문을 보내세요.',
    markerEmoji: '🐘',
    highlights: ['코끼리 생츄어리 체험', '도이수텝 사원 일출', '선데이 나이트마켓'],
    costBreakdown: {
      flight: { min: 500_000, max: 900_000 },
      accommodation: { min: 1_000_000, max: 2_300_000 },
      local: { min: 1_000_000, max: 1_800_000 },
    },
  },
  {
    id: 'hoi-an',
    name: '호이안',
    nameEn: 'Hoi An',
    region: '동남아',
    coordinates: [108.33, 15.88],
    concepts: ['관광', '휴양'],
    accommodationTypes: ['리조트', '호텔', '에어비앤비'],
    budgetRange: { min: 2_500_000, max: 5_000_000 },
    nights: 5,
    features: ['올드타운 등불', '맞춤 의상', '바구니배', '안방 비치'],
    bestBookingWeeks: 6,
    visaRequired: false,
    description: '수백 개의 등불이 빛나는 올드타운에서 감성 넘치는 허니문을 즐기세요.',
    markerEmoji: '🏮',
    highlights: ['등불 올드타운 야경', '바구니배 체험', '맞춤 아오자이 제작'],
    costBreakdown: {
      flight: { min: 500_000, max: 900_000 },
      accommodation: { min: 1_000_000, max: 2_500_000 },
      local: { min: 1_000_000, max: 1_600_000 },
    },
  },
  {
    id: 'langkawi',
    name: '랑카위',
    nameEn: 'Langkawi',
    region: '동남아',
    coordinates: [99.72, 6.35],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['리조트', '호텔'],
    budgetRange: { min: 2_500_000, max: 5_500_000 },
    nights: 5,
    features: ['스카이브릿지', '맹그로브 투어', '면세 쇼핑', '선셋 크루즈'],
    bestBookingWeeks: 6,
    visaRequired: false,
    description: '말레이시아의 보석 같은 면세 섬에서 자연과 함께하는 휴양을 즐기세요.',
    markerEmoji: '🦅',
    highlights: ['스카이브릿지 케이블카', '맹그로브 보트 투어', '탄중루 비치 선셋'],
    costBreakdown: {
      flight: { min: 600_000, max: 1_100_000 },
      accommodation: { min: 1_000_000, max: 2_800_000 },
      local: { min: 900_000, max: 1_600_000 },
    },
  },
  {
    id: 'kota-kinabalu',
    name: '코타키나발루',
    nameEn: 'Kota Kinabalu',
    region: '동남아',
    coordinates: [116.07, 5.98],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['리조트', '호텔'],
    budgetRange: { min: 2_500_000, max: 5_500_000 },
    nights: 5,
    features: ['키나발루산', '섬 호핑투어', '반딧불 투어', '세계 3대 석양'],
    bestBookingWeeks: 6,
    visaRequired: false,
    description: '세계 3대 석양으로 유명한 보르네오 섬에서 자연 속 허니문을 즐기세요.',
    markerEmoji: '🌅',
    highlights: ['세계 3대 석양 감상', '사피섬 스노클링', '반딧불 리버크루즈'],
    costBreakdown: {
      flight: { min: 500_000, max: 1_000_000 },
      accommodation: { min: 1_000_000, max: 2_800_000 },
      local: { min: 1_000_000, max: 1_700_000 },
    },
  },
  {
    id: 'nha-trang',
    name: '나트랑',
    nameEn: 'Nha Trang',
    region: '동남아',
    coordinates: [109.19, 12.24],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['리조트', '호텔'],
    budgetRange: { min: 2_500_000, max: 5_000_000 },
    nights: 5,
    features: ['빈펄랜드', '머드 스파', '섬 투어', '해산물 맛집'],
    bestBookingWeeks: 6,
    visaRequired: false,
    description: '베트남 최고의 해변 도시에서 머드 스파와 섬 투어를 즐기세요.',
    markerEmoji: '🏊',
    highlights: ['빈펄랜드 워터파크', '머드 온천 스파', '혼몽섬 스노클링'],
    costBreakdown: {
      flight: { min: 500_000, max: 900_000 },
      accommodation: { min: 1_000_000, max: 2_500_000 },
      local: { min: 1_000_000, max: 1_600_000 },
    },
  },
  {
    id: 'palawan',
    name: '팔라완',
    nameEn: 'Palawan',
    region: '동남아',
    coordinates: [118.73, 9.84],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['리조트', '에어비앤비'],
    budgetRange: { min: 3_000_000, max: 6_000_000 },
    nights: 6,
    features: ['엘니도 라군', '언더그라운드 리버', '아일랜드 호핑', '카약'],
    bestBookingWeeks: 8,
    visaRequired: false,
    description: '세계 최고의 섬으로 선정된 팔라완의 비밀 라군을 탐험하세요.',
    markerEmoji: '🛶',
    highlights: ['엘니도 빅라군 카약', '지하강 동굴 투어', '나클판 비치 캠핑'],
    costBreakdown: {
      flight: { min: 600_000, max: 1_200_000 },
      accommodation: { min: 1_400_000, max: 3_000_000 },
      local: { min: 1_000_000, max: 1_800_000 },
    },
  },
  {
    id: 'lombok',
    name: '롬복',
    nameEn: 'Lombok',
    region: '동남아',
    coordinates: [116.32, -8.65],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['풀빌라', '리조트'],
    budgetRange: { min: 3_000_000, max: 6_000_000 },
    nights: 6,
    features: ['길리 트라왕안', '린자니 화산', '핑크비치', '서핑'],
    bestBookingWeeks: 8,
    visaRequired: false,
    description: '발리의 조용한 이웃 섬에서 길리 아일랜드와 핑크비치를 만나세요.',
    markerEmoji: '🌋',
    highlights: ['길리섬 스노클링', '핑크비치 일출', '린자니산 트레킹'],
    costBreakdown: {
      flight: { min: 800_000, max: 1_500_000 },
      accommodation: { min: 1_200_000, max: 2_800_000 },
      local: { min: 1_000_000, max: 1_700_000 },
    },
  },
  {
    id: 'siem-reap',
    name: '시엠립',
    nameEn: 'Siem Reap',
    region: '동남아',
    coordinates: [103.86, 13.36],
    concepts: ['관광', '액티비티'],
    accommodationTypes: ['리조트', '호텔'],
    budgetRange: { min: 2_500_000, max: 5_000_000 },
    nights: 5,
    features: ['앙코르와트', '톤레삽 호수', '펍스트리트', '일출 투어'],
    bestBookingWeeks: 6,
    visaRequired: false,
    description: '세계 7대 불가사의 앙코르와트에서 신비로운 일출을 함께 감상하세요.',
    markerEmoji: '🛕',
    highlights: ['앙코르와트 일출', '톤레삽 수상마을', '앙코르톰 바이욘 사원'],
    costBreakdown: {
      flight: { min: 500_000, max: 900_000 },
      accommodation: { min: 1_000_000, max: 2_500_000 },
      local: { min: 1_000_000, max: 1_600_000 },
    },
  },
  {
    id: 'luang-prabang',
    name: '루앙프라방',
    nameEn: 'Luang Prabang',
    region: '동남아',
    coordinates: [102.13, 19.89],
    concepts: ['관광', '휴양'],
    accommodationTypes: ['리조트', '호텔', '에어비앤비'],
    budgetRange: { min: 2_500_000, max: 5_000_000 },
    nights: 5,
    features: ['탁발 의식', '꽝시 폭포', '메콩강 크루즈', '야시장'],
    bestBookingWeeks: 6,
    visaRequired: false,
    description: '유네스코 세계유산 도시에서 메콩강의 여유를 느끼세요.',
    markerEmoji: '🙏',
    highlights: ['새벽 탁발 의식', '꽝시 폭포 수영', '메콩강 선셋 크루즈'],
    costBreakdown: {
      flight: { min: 600_000, max: 1_100_000 },
      accommodation: { min: 1_000_000, max: 2_300_000 },
      local: { min: 900_000, max: 1_600_000 },
    },
  },
  {
    id: 'bintan',
    name: '빈탄',
    nameEn: 'Bintan',
    region: '동남아',
    coordinates: [104.52, 1.08],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['리조트', '풀빌라'],
    budgetRange: { min: 3_000_000, max: 6_000_000 },
    nights: 4,
    features: ['골프', '맹그로브 투어', '워터스포츠', '리조트 스파'],
    bestBookingWeeks: 6,
    visaRequired: false,
    description: '싱가포르에서 페리로 1시간, 가까운 열대 리조트 아일랜드입니다.',
    markerEmoji: '⛳',
    highlights: ['프라이빗 비치 리조트', '맹그로브 카약', '골프 라운딩'],
    costBreakdown: {
      flight: { min: 600_000, max: 1_100_000 },
      accommodation: { min: 1_400_000, max: 3_200_000 },
      local: { min: 1_000_000, max: 1_700_000 },
    },
  },
  {
    id: 'phi-phi',
    name: '피피섬',
    nameEn: 'Phi Phi Islands',
    region: '동남아',
    coordinates: [98.77, 7.74],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['리조트', '호텔'],
    budgetRange: { min: 3_000_000, max: 6_000_000 },
    nights: 5,
    features: ['마야 베이', '스노클링', '뷰포인트', '비치 파티'],
    bestBookingWeeks: 8,
    visaRequired: false,
    description: '영화 "더 비치"의 배경이 된 마야 베이에서 꿈같은 시간을 보내세요.',
    markerEmoji: '🎬',
    highlights: ['마야 베이 스노클링', '피피섬 뷰포인트 트레킹', '롱테일 보트 투어'],
    costBreakdown: {
      flight: { min: 600_000, max: 1_200_000 },
      accommodation: { min: 1_400_000, max: 3_000_000 },
      local: { min: 1_000_000, max: 1_800_000 },
    },
  },
  {
    id: 'coron',
    name: '코론',
    nameEn: 'Coron',
    region: '동남아',
    coordinates: [120.2, 11.99],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['리조트', '에어비앤비'],
    budgetRange: { min: 3_000_000, max: 6_000_000 },
    nights: 5,
    features: ['난파선 다이빙', '카얀간 레이크', '트윈 라군', '섬 투어'],
    bestBookingWeeks: 8,
    visaRequired: false,
    description: '필리핀의 숨겨진 보석, 난파선 다이빙과 에메랄드 호수의 천국입니다.',
    markerEmoji: '🤿',
    highlights: ['카얀간 레이크 스노클링', '난파선 다이빙', '트윈 라군 카약'],
    costBreakdown: {
      flight: { min: 600_000, max: 1_200_000 },
      accommodation: { min: 1_400_000, max: 3_000_000 },
      local: { min: 1_000_000, max: 1_800_000 },
    },
  },
  {
    id: 'koh-tao',
    name: '코타오',
    nameEn: 'Koh Tao',
    region: '동남아',
    coordinates: [99.84, 10.1],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['리조트', '에어비앤비'],
    budgetRange: { min: 2_500_000, max: 5_000_000 },
    nights: 5,
    features: ['스쿠버 다이빙', '스노클링', '뷰포인트', '비치 요가'],
    bestBookingWeeks: 6,
    visaRequired: false,
    description: '세계적인 다이빙 명소에서 바다 속 신비로운 세계를 함께 탐험하세요.',
    markerEmoji: '🐢',
    highlights: ['오픈워터 다이빙 자격증', '난위안섬 스노클링', '망고 베이 선셋'],
    costBreakdown: {
      flight: { min: 600_000, max: 1_100_000 },
      accommodation: { min: 1_000_000, max: 2_300_000 },
      local: { min: 900_000, max: 1_600_000 },
    },
  },
  {
    id: 'hanoi',
    name: '하노이',
    nameEn: 'Hanoi',
    region: '동남아',
    coordinates: [105.85, 21.03],
    concepts: ['관광', '쇼핑'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 2_500_000, max: 4_500_000 },
    nights: 5,
    features: ['하롱베이', '올드쿼터', '호안끼엠 호수', '쌀국수 맛집'],
    bestBookingWeeks: 6,
    visaRequired: false,
    description: '천년 역사의 수도에서 하롱베이 크루즈와 올드쿼터의 매력을 느끼세요.',
    markerEmoji: '🚢',
    highlights: ['하롱베이 1박 크루즈', '올드쿼터 거리 탐험', '분짜 & 쌀국수 맛집 투어'],
    costBreakdown: {
      flight: { min: 400_000, max: 800_000 },
      accommodation: { min: 1_000_000, max: 2_200_000 },
      local: { min: 1_100_000, max: 1_500_000 },
    },
  },
  {
    id: 'hua-hin',
    name: '후아힌',
    nameEn: 'Hua Hin',
    region: '동남아',
    coordinates: [99.96, 12.57],
    concepts: ['휴양', '관광'],
    accommodationTypes: ['리조트', '호텔'],
    budgetRange: { min: 2_500_000, max: 5_000_000 },
    nights: 5,
    features: ['왕실 휴양지', '야시장', '빈티지 기차역', '골프'],
    bestBookingWeeks: 6,
    visaRequired: false,
    description: '태국 왕실의 휴양지에서 고급스럽고 여유로운 허니문을 보내세요.',
    markerEmoji: '👑',
    highlights: ['후아힌 비치 승마', '시세짓 야시장', '마루카타이원 궁전'],
    costBreakdown: {
      flight: { min: 500_000, max: 900_000 },
      accommodation: { min: 1_000_000, max: 2_500_000 },
      local: { min: 1_000_000, max: 1_600_000 },
    },
  },

  // ═══════════════════════════════════════════════════════
  // 동아시아 (12)
  // ═══════════════════════════════════════════════════════
  {
    id: 'okinawa',
    name: '오키나와',
    nameEn: 'Okinawa',
    region: '동아시아',
    coordinates: [127.68, 26.34],
    concepts: ['휴양', '관광', '액티비티'],
    accommodationTypes: ['리조트', '호텔'],
    budgetRange: { min: 3_000_000, max: 6_000_000 },
    nights: 5,
    features: ['츄라우미 수족관', '만좌모', '스노클링', '소키소바'],
    bestBookingWeeks: 8,
    visaRequired: false,
    description: '일본 남단의 열대 섬에서 에메랄드빛 바다와 류큐 문화를 즐기세요.',
    markerEmoji: '🐠',
    highlights: ['츄라우미 수족관 관람', '만좌모 절벽 일출', '케라마 제도 스노클링'],
    costBreakdown: {
      flight: { min: 600_000, max: 1_200_000 },
      accommodation: { min: 1_400_000, max: 3_000_000 },
      local: { min: 1_000_000, max: 1_800_000 },
    },
  },
  {
    id: 'tokyo',
    name: '도쿄',
    nameEn: 'Tokyo',
    region: '동아시아',
    coordinates: [139.69, 35.69],
    concepts: ['관광', '쇼핑'],
    accommodationTypes: ['호텔'],
    budgetRange: { min: 3_000_000, max: 6_000_000 },
    nights: 5,
    features: ['시부야', '아사쿠사', '디즈니랜드', '오모테산도'],
    bestBookingWeeks: 8,
    visaRequired: false,
    description: '전통과 최첨단이 공존하는 대도시에서 먹방과 쇼핑을 즐기세요.',
    markerEmoji: '🗼',
    highlights: ['시부야 스크램블 & 하라주쿠', '도쿄 디즈니랜드', '츠키지 & 긴자 미식 투어'],
    costBreakdown: {
      flight: { min: 500_000, max: 1_000_000 },
      accommodation: { min: 1_500_000, max: 3_000_000 },
      local: { min: 1_000_000, max: 2_000_000 },
    },
  },
  {
    id: 'kyoto',
    name: '교토',
    nameEn: 'Kyoto',
    region: '동아시아',
    coordinates: [135.77, 35.01],
    concepts: ['관광', '휴양'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 3_000_000, max: 6_000_000 },
    nights: 5,
    features: ['후시미이나리', '아라시야마', '기온거리', '료칸 체험'],
    bestBookingWeeks: 8,
    visaRequired: false,
    description: '천년 고도의 붉은 도리이와 대나무 숲에서 일본의 정취를 느끼세요.',
    markerEmoji: '⛩️',
    highlights: ['후시미이나리 천 개의 도리이', '아라시야마 대나무 숲', '기온 게이샤 거리'],
    costBreakdown: {
      flight: { min: 500_000, max: 1_000_000 },
      accommodation: { min: 1_500_000, max: 3_000_000 },
      local: { min: 1_000_000, max: 2_000_000 },
    },
  },
  {
    id: 'hokkaido',
    name: '홋카이도',
    nameEn: 'Hokkaido',
    region: '동아시아',
    coordinates: [141.35, 43.06],
    concepts: ['관광', '휴양', '액티비티'],
    accommodationTypes: ['리조트', '호텔'],
    budgetRange: { min: 3_500_000, max: 7_000_000 },
    nights: 6,
    features: ['라벤더 팜', '온천 료칸', '해산물 맛집', '스키'],
    bestBookingWeeks: 10,
    visaRequired: false,
    description: '사계절 매력이 넘치는 홋카이도에서 온천과 미식의 허니문을 보내세요.',
    markerEmoji: '🏔️',
    highlights: ['후라노 라벤더 팜', '삿포로 해산물 시장', '노보리베츠 온천'],
    costBreakdown: {
      flight: { min: 600_000, max: 1_200_000 },
      accommodation: { min: 1_700_000, max: 3_500_000 },
      local: { min: 1_200_000, max: 2_300_000 },
    },
  },
  {
    id: 'osaka',
    name: '오사카',
    nameEn: 'Osaka',
    region: '동아시아',
    coordinates: [135.5, 34.69],
    concepts: ['관광', '쇼핑'],
    accommodationTypes: ['호텔'],
    budgetRange: { min: 2_500_000, max: 5_500_000 },
    nights: 5,
    features: ['도톤보리', '유니버설 스튜디오', '오사카성', '구로몬 시장'],
    bestBookingWeeks: 8,
    visaRequired: false,
    description: '일본의 식도락 수도에서 먹방과 놀이공원을 동시에 즐기세요.',
    markerEmoji: '🏯',
    highlights: ['도톤보리 먹방 투어', '유니버설 스튜디오 재팬', '오사카성 야경'],
    costBreakdown: {
      flight: { min: 400_000, max: 900_000 },
      accommodation: { min: 1_200_000, max: 2_800_000 },
      local: { min: 900_000, max: 1_800_000 },
    },
  },
  {
    id: 'fukuoka',
    name: '후쿠오카',
    nameEn: 'Fukuoka',
    region: '동아시아',
    coordinates: [130.42, 33.59],
    concepts: ['관광', '쇼핑'],
    accommodationTypes: ['호텔'],
    budgetRange: { min: 2_000_000, max: 4_500_000 },
    nights: 4,
    features: ['하카타 라멘', '캐널시티', '다자이후 텐만구', '야타이 포장마차'],
    bestBookingWeeks: 6,
    visaRequired: false,
    description: '한국에서 가장 가까운 일본, 하카타 라멘과 야타이 투어를 즐기세요.',
    markerEmoji: '🍜',
    highlights: ['하카타 라멘 맛집 투어', '다자이후 텐만구 참배', '나카스 야타이 포장마차'],
    costBreakdown: {
      flight: { min: 300_000, max: 700_000 },
      accommodation: { min: 1_000_000, max: 2_200_000 },
      local: { min: 700_000, max: 1_600_000 },
    },
  },
  {
    id: 'miyako-jima',
    name: '미야코지마',
    nameEn: 'Miyako-jima',
    region: '동아시아',
    coordinates: [125.28, 24.79],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['리조트', '호텔'],
    budgetRange: { min: 3_500_000, max: 7_000_000 },
    nights: 5,
    features: ['요나하마에하마 비치', '이라부 대교', '다이빙', '망고 빙수'],
    bestBookingWeeks: 10,
    visaRequired: false,
    description: '일본 최고의 투명한 바다, 미야코블루를 직접 만나보세요.',
    markerEmoji: '💎',
    highlights: ['요나하마에하마 비치', '이라부 대교 드라이브', '시기라 비치 스노클링'],
    costBreakdown: {
      flight: { min: 700_000, max: 1_400_000 },
      accommodation: { min: 1_600_000, max: 3_500_000 },
      local: { min: 1_200_000, max: 2_100_000 },
    },
  },
  {
    id: 'taipei',
    name: '타이베이',
    nameEn: 'Taipei',
    region: '동아시아',
    coordinates: [121.56, 25.03],
    concepts: ['관광', '쇼핑'],
    accommodationTypes: ['호텔'],
    budgetRange: { min: 2_000_000, max: 4_000_000 },
    nights: 4,
    features: ['지우펀', '101 타워', '야시장', '딘타이펑 딤섬'],
    bestBookingWeeks: 4,
    visaRequired: false,
    description: '야시장 천국 타이베이에서 맛집과 쇼핑을 마음껏 즐기세요.',
    markerEmoji: '🧋',
    highlights: ['지우펀 올드스트릿', '타이베이 101 전망대', '스린 야시장 먹방'],
    costBreakdown: {
      flight: { min: 300_000, max: 600_000 },
      accommodation: { min: 900_000, max: 2_000_000 },
      local: { min: 800_000, max: 1_400_000 },
    },
  },
  {
    id: 'hong-kong',
    name: '홍콩',
    nameEn: 'Hong Kong',
    region: '동아시아',
    coordinates: [114.17, 22.32],
    concepts: ['관광', '쇼핑'],
    accommodationTypes: ['호텔'],
    budgetRange: { min: 2_500_000, max: 5_000_000 },
    nights: 4,
    features: ['빅토리아 피크', '스타페리', '딤섬', '란콰이펑'],
    bestBookingWeeks: 6,
    visaRequired: false,
    description: '100만 달러 야경과 미슐랭 딤섬이 기다리는 아시아의 보석입니다.',
    markerEmoji: '🌃',
    highlights: ['빅토리아 피크 야경', '스타페리 크루즈', '침사추이 심포니 오브 라이트'],
    costBreakdown: {
      flight: { min: 400_000, max: 800_000 },
      accommodation: { min: 1_200_000, max: 2_700_000 },
      local: { min: 900_000, max: 1_500_000 },
    },
  },
  {
    id: 'macau',
    name: '마카오',
    nameEn: 'Macau',
    region: '동아시아',
    coordinates: [113.54, 22.2],
    concepts: ['관광', '쇼핑'],
    accommodationTypes: ['호텔', '리조트'],
    budgetRange: { min: 2_500_000, max: 5_000_000 },
    nights: 3,
    features: ['세나도 광장', '베네시안 리조트', '에그타르트', '번지점프'],
    bestBookingWeeks: 4,
    visaRequired: false,
    description: '포르투갈과 중국 문화가 어우러진 동양의 라스베이거스를 만나세요.',
    markerEmoji: '🎰',
    highlights: ['세나도 광장 & 성 바울 성당', '베네시안 리조트', '마카오 타워 번지점프'],
    costBreakdown: {
      flight: { min: 400_000, max: 800_000 },
      accommodation: { min: 1_200_000, max: 2_700_000 },
      local: { min: 900_000, max: 1_500_000 },
    },
  },
  {
    id: 'karuizawa',
    name: '카루이자와',
    nameEn: 'Karuizawa',
    region: '동아시아',
    coordinates: [136.56, 36.35],
    concepts: ['휴양', '관광'],
    accommodationTypes: ['호텔', '리조트'],
    budgetRange: { min: 3_000_000, max: 6_000_000 },
    nights: 4,
    features: ['시라이토 폭포', '구 카루이자와', '자전거 투어', '아울렛'],
    bestBookingWeeks: 8,
    visaRequired: false,
    description: '도쿄 근교 고원 리조트에서 자연 속 로맨틱한 휴식을 즐기세요.',
    markerEmoji: '🍂',
    highlights: ['시라이토 폭포 산책', '구 카루이자와 은행나무길', '호시노 리조트 온천'],
    costBreakdown: {
      flight: { min: 500_000, max: 1_000_000 },
      accommodation: { min: 1_500_000, max: 3_200_000 },
      local: { min: 1_000_000, max: 1_800_000 },
    },
  },
  {
    id: 'ishigaki',
    name: '이시가키',
    nameEn: 'Ishigaki',
    region: '동아시아',
    coordinates: [124.16, 24.34],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['리조트', '호텔'],
    budgetRange: { min: 3_500_000, max: 7_000_000 },
    nights: 5,
    features: ['카비라만', '만타 다이빙', '다케토미섬', '이시가키 소고기'],
    bestBookingWeeks: 10,
    visaRequired: false,
    description: '일본 최남단 산호초 바다에서 만타레이와 함께 다이빙하세요.',
    markerEmoji: '🐙',
    highlights: ['카비라만 글래스보트', '만타 스크램블 다이빙', '다케토미섬 수우차'],
    costBreakdown: {
      flight: { min: 700_000, max: 1_400_000 },
      accommodation: { min: 1_600_000, max: 3_500_000 },
      local: { min: 1_200_000, max: 2_100_000 },
    },
  },

  // ═══════════════════════════════════════════════════════
  // 남아시아/인도양 (5 total — maldives 위에 이미 포함, 나머지 4)
  // ═══════════════════════════════════════════════════════
  {
    id: 'mauritius',
    name: '모리셔스',
    nameEn: 'Mauritius',
    region: '남아시아/인도양',
    coordinates: [57.55, -20.35],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['리조트', '풀빌라'],
    budgetRange: { min: 7_000_000, max: 13_000_000 },
    nights: 7,
    features: ['7색 대지', '일 오 세르프', '돌고래 투어', '르 몬 브라방'],
    bestBookingWeeks: 12,
    visaRequired: false,
    description: '인도양의 천국, 7색 대지와 터콰이즈 바다가 어우러진 꿈의 섬입니다.',
    markerEmoji: '🌈',
    highlights: ['7색 대지 관광', '일 오 세르프 비치', '돌고래 스위밍'],
    costBreakdown: {
      flight: { min: 2_000_000, max: 3_500_000 },
      accommodation: { min: 3_500_000, max: 6_500_000 },
      local: { min: 1_500_000, max: 3_000_000 },
    },
  },
  {
    id: 'seychelles',
    name: '세이셸',
    nameEn: 'Seychelles',
    region: '남아시아/인도양',
    coordinates: [55.45, -4.68],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['리조트', '풀빌라'],
    budgetRange: { min: 8_000_000, max: 15_000_000 },
    nights: 7,
    features: ['앙스 수스 다정', '프라슬린 섬', '자이언트 거북', '프라이빗 비치'],
    bestBookingWeeks: 14,
    visaRequired: false,
    description: '영국 왕실도 찾는 인도양의 에덴동산에서 극상의 허니문을 즐기세요.',
    markerEmoji: '🐢',
    highlights: ['앙스 수스 다정 비치', '발레 드 메 자연보호구역', '프라이빗 아일랜드 디너'],
    costBreakdown: {
      flight: { min: 2_500_000, max: 4_000_000 },
      accommodation: { min: 4_000_000, max: 8_000_000 },
      local: { min: 1_500_000, max: 3_000_000 },
    },
  },
  {
    id: 'sri-lanka',
    name: '스리랑카',
    nameEn: 'Sri Lanka',
    region: '남아시아/인도양',
    coordinates: [80.77, 7.87],
    concepts: ['관광', '액티비티', '휴양'],
    accommodationTypes: ['리조트', '호텔', '에어비앤비'],
    budgetRange: { min: 4_000_000, max: 8_000_000 },
    nights: 7,
    features: ['시기리야 바위', '기차 여행', '고래 관찰', '아유르베다 스파'],
    bestBookingWeeks: 8,
    visaRequired: false,
    description: '고대 유적과 열대 자연이 공존하는 인도양의 눈물방울 섬입니다.',
    markerEmoji: '🚂',
    highlights: ['시기리야 라이언 락', '캔디-엘라 기차 투어', '미리사 고래 와칭'],
    costBreakdown: {
      flight: { min: 1_000_000, max: 2_000_000 },
      accommodation: { min: 1_500_000, max: 3_500_000 },
      local: { min: 1_500_000, max: 2_500_000 },
    },
  },
  {
    id: 'goa',
    name: '고아',
    nameEn: 'Goa',
    region: '남아시아/인도양',
    coordinates: [74.12, 15.3],
    concepts: ['휴양', '관광'],
    accommodationTypes: ['리조트', '호텔', '에어비앤비'],
    budgetRange: { min: 4_000_000, max: 8_000_000 },
    nights: 6,
    features: ['포르투갈 건축', '비치 파티', '스파이스 농장', '해산물'],
    bestBookingWeeks: 8,
    visaRequired: true,
    description: '인도 서해안의 포르투갈풍 해변 도시에서 이국적인 허니문을 즐기세요.',
    markerEmoji: '🌶️',
    highlights: ['올드고아 포르투갈 성당', '팔로렘 비치 선셋', '스파이스 농장 투어'],
    costBreakdown: {
      flight: { min: 1_000_000, max: 2_000_000 },
      accommodation: { min: 1_500_000, max: 3_500_000 },
      local: { min: 1_500_000, max: 2_500_000 },
    },
  },

  // ═══════════════════════════════════════════════════════
  // 유럽 (26 total — europe 위에 이미 포함, 나머지 25)
  // ═══════════════════════════════════════════════════════
  {
    id: 'paris',
    name: '파리',
    nameEn: 'Paris',
    region: '유럽',
    coordinates: [2.35, 48.86],
    concepts: ['관광', '쇼핑'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 5_500_000, max: 11_000_000 },
    nights: 7,
    features: ['에펠탑', '루브르 박물관', '샹젤리제', '세느강 크루즈'],
    bestBookingWeeks: 14,
    visaRequired: false,
    description: '세상에서 가장 로맨틱한 도시, 파리에서 사랑을 속삭이세요.',
    markerEmoji: '🗼',
    highlights: ['에펠탑 야경 디너', '루브르 박물관 투어', '세느강 선셋 크루즈'],
    costBreakdown: {
      flight: { min: 1_500_000, max: 2_500_000 },
      accommodation: { min: 2_500_000, max: 5_500_000 },
      local: { min: 1_500_000, max: 3_000_000 },
    },
  },
  {
    id: 'rome',
    name: '로마',
    nameEn: 'Rome',
    region: '유럽',
    coordinates: [12.5, 41.9],
    concepts: ['관광', '쇼핑'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 5_000_000, max: 10_000_000 },
    nights: 7,
    features: ['콜로세움', '바티칸', '트레비 분수', '젤라토'],
    bestBookingWeeks: 14,
    visaRequired: false,
    description: '영원의 도시 로마에서 2000년 역사와 미식을 동시에 즐기세요.',
    markerEmoji: '🏛️',
    highlights: ['콜로세움 & 포로 로마노', '바티칸 시스티나 성당', '트레비 분수 동전 던지기'],
    costBreakdown: {
      flight: { min: 1_400_000, max: 2_400_000 },
      accommodation: { min: 2_200_000, max: 4_800_000 },
      local: { min: 1_400_000, max: 2_800_000 },
    },
  },
  {
    id: 'barcelona',
    name: '바르셀로나',
    nameEn: 'Barcelona',
    region: '유럽',
    coordinates: [2.17, 41.39],
    concepts: ['관광', '쇼핑', '액티비티'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 5_000_000, max: 10_000_000 },
    nights: 7,
    features: ['사그라다 파밀리아', '람블라스 거리', '바르셀로네타 비치', '가우디 건축'],
    bestBookingWeeks: 14,
    visaRequired: false,
    description: '가우디의 건축과 지중해 해변이 어우러진 열정의 도시입니다.',
    markerEmoji: '🎭',
    highlights: ['사그라다 파밀리아 내부 투어', '구엘 공원 모자이크', '보케리아 시장 먹방'],
    costBreakdown: {
      flight: { min: 1_400_000, max: 2_400_000 },
      accommodation: { min: 2_200_000, max: 4_800_000 },
      local: { min: 1_400_000, max: 2_800_000 },
    },
  },
  {
    id: 'santorini',
    name: '산토리니',
    nameEn: 'Santorini',
    region: '유럽',
    coordinates: [25.43, 36.39],
    concepts: ['휴양', '관광'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 6_000_000, max: 12_000_000 },
    nights: 6,
    features: ['이아 석양', '블루돔 성당', '와이너리', '칼데라 뷰'],
    bestBookingWeeks: 16,
    visaRequired: false,
    description: '새하얀 건물과 파란 지붕 사이로 세계 최고의 석양을 감상하세요.',
    markerEmoji: '🏛️',
    highlights: ['이아 선셋 포인트', '칼데라 클리프 호텔', '와이너리 투어'],
    costBreakdown: {
      flight: { min: 1_500_000, max: 2_500_000 },
      accommodation: { min: 3_000_000, max: 6_500_000 },
      local: { min: 1_500_000, max: 3_000_000 },
    },
  },
  {
    id: 'prague',
    name: '프라하',
    nameEn: 'Prague',
    region: '유럽',
    coordinates: [14.42, 50.08],
    concepts: ['관광', '쇼핑'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 5_000_000, max: 9_000_000 },
    nights: 6,
    features: ['카를교', '프라하 성', '올드타운 광장', '체코 맥주'],
    bestBookingWeeks: 12,
    visaRequired: false,
    description: '동화 속 중세 도시에서 카를교의 야경을 함께 걸어보세요.',
    markerEmoji: '🏰',
    highlights: ['카를교 일출 산책', '프라하 성 투어', '올드타운 천문시계'],
    costBreakdown: {
      flight: { min: 1_400_000, max: 2_300_000 },
      accommodation: { min: 2_000_000, max: 4_000_000 },
      local: { min: 1_600_000, max: 2_700_000 },
    },
  },
  {
    id: 'london',
    name: '런던',
    nameEn: 'London',
    region: '유럽',
    coordinates: [-0.13, 51.51],
    concepts: ['관광', '쇼핑'],
    accommodationTypes: ['호텔'],
    budgetRange: { min: 6_000_000, max: 12_000_000 },
    nights: 7,
    features: ['빅벤', '대영박물관', '해리포터 스튜디오', '애프터눈 티'],
    bestBookingWeeks: 14,
    visaRequired: false,
    description: '왕실의 품격과 현대적 감각이 공존하는 세계적인 문화 수도입니다.',
    markerEmoji: '💂',
    highlights: ['버킹엄 궁전 근위병 교대식', '해리포터 스튜디오 투어', '런던아이 야경'],
    costBreakdown: {
      flight: { min: 1_500_000, max: 2_500_000 },
      accommodation: { min: 2_800_000, max: 6_000_000 },
      local: { min: 1_700_000, max: 3_500_000 },
    },
  },
  {
    id: 'interlaken',
    name: '인터라켄',
    nameEn: 'Interlaken',
    region: '유럽',
    coordinates: [7.86, 46.69],
    concepts: ['관광', '액티비티'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 6_000_000, max: 12_000_000 },
    nights: 6,
    features: ['융프라우', '패러글라이딩', '호수 크루즈', '알프스 트레킹'],
    bestBookingWeeks: 14,
    visaRequired: false,
    description: '알프스 만년설과 에메랄드 호수가 만나는 스위스의 심장입니다.',
    markerEmoji: '🏔️',
    highlights: ['융프라우 톱 오브 유럽', '인터라켄 패러글라이딩', '툰 호수 크루즈'],
    costBreakdown: {
      flight: { min: 1_500_000, max: 2_500_000 },
      accommodation: { min: 2_500_000, max: 5_500_000 },
      local: { min: 2_000_000, max: 4_000_000 },
    },
  },
  {
    id: 'dubrovnik',
    name: '두브로브니크',
    nameEn: 'Dubrovnik',
    region: '유럽',
    coordinates: [18.09, 42.65],
    concepts: ['관광', '휴양'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 5_500_000, max: 10_000_000 },
    nights: 6,
    features: ['성벽 투어', '케이블카', '구시가지', '아드리아해 비치'],
    bestBookingWeeks: 12,
    visaRequired: false,
    description: '왕좌의 게임 촬영지, 아드리아해의 진주에서 낭만을 느끼세요.',
    markerEmoji: '🏰',
    highlights: ['구시가지 성벽 일주', '스르지산 케이블카 전망', '로크룸 섬 투어'],
    costBreakdown: {
      flight: { min: 1_500_000, max: 2_500_000 },
      accommodation: { min: 2_300_000, max: 4_800_000 },
      local: { min: 1_700_000, max: 2_700_000 },
    },
  },
  {
    id: 'lisbon',
    name: '리스본',
    nameEn: 'Lisbon',
    region: '유럽',
    coordinates: [-9.14, 38.74],
    concepts: ['관광', '쇼핑'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 5_000_000, max: 9_500_000 },
    nights: 6,
    features: ['트램 28번', '벨렘 타워', '파두 공연', '에그타르트'],
    bestBookingWeeks: 12,
    visaRequired: false,
    description: '대항해 시대의 영광이 살아있는 언덕 위 도시에서 파두를 들으세요.',
    markerEmoji: '🚃',
    highlights: ['트램 28번 투어', '벨렘 타워 & 제로니무스 수도원', '알파마 지구 파두 공연'],
    costBreakdown: {
      flight: { min: 1_400_000, max: 2_300_000 },
      accommodation: { min: 2_000_000, max: 4_200_000 },
      local: { min: 1_600_000, max: 3_000_000 },
    },
  },
  {
    id: 'amalfi',
    name: '아말피',
    nameEn: 'Amalfi Coast',
    region: '유럽',
    coordinates: [14.6, 40.63],
    concepts: ['휴양', '관광'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 6_000_000, max: 13_000_000 },
    nights: 6,
    features: ['포지타노', '레몬첼로', '절벽 드라이브', '카프리 섬'],
    bestBookingWeeks: 14,
    visaRequired: false,
    description: '절벽에 매달린 파스텔 마을과 지중해의 푸른 바다가 만나는 곳입니다.',
    markerEmoji: '🍋',
    highlights: ['포지타노 절벽 마을', '카프리 섬 블루그로토', '아말피 해안 드라이브'],
    costBreakdown: {
      flight: { min: 1_500_000, max: 2_500_000 },
      accommodation: { min: 2_800_000, max: 7_000_000 },
      local: { min: 1_700_000, max: 3_500_000 },
    },
  },
  {
    id: 'nice',
    name: '니스',
    nameEn: 'Nice',
    region: '유럽',
    coordinates: [7.26, 43.7],
    concepts: ['휴양', '관광'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 5_500_000, max: 11_000_000 },
    nights: 6,
    features: ['프롬나드 데 장글레', '에즈 마을', '모나코', '코트다쥐르'],
    bestBookingWeeks: 12,
    visaRequired: false,
    description: '코트다쥐르 해안을 따라 모나코까지, 남프랑스의 매력에 빠져보세요.',
    markerEmoji: '🎨',
    highlights: ['프롬나드 데 장글레 해변 산책', '에즈 중세마을 전망대', '모나코 몬테카를로 카지노'],
    costBreakdown: {
      flight: { min: 1_500_000, max: 2_500_000 },
      accommodation: { min: 2_500_000, max: 5_500_000 },
      local: { min: 1_500_000, max: 3_000_000 },
    },
  },
  {
    id: 'florence',
    name: '피렌체',
    nameEn: 'Florence',
    region: '유럽',
    coordinates: [11.25, 43.77],
    concepts: ['관광', '쇼핑'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 5_000_000, max: 10_000_000 },
    nights: 6,
    features: ['우피치 미술관', '두오모', '베키오 다리', '피렌체 스테이크'],
    bestBookingWeeks: 12,
    visaRequired: false,
    description: '르네상스의 발상지에서 예술과 미식의 로맨틱 여행을 즐기세요.',
    markerEmoji: '🎨',
    highlights: ['우피치 미술관 투어', '두오모 쿠폴라 전망', '베키오 다리 보석 상점 산책'],
    costBreakdown: {
      flight: { min: 1_400_000, max: 2_400_000 },
      accommodation: { min: 2_200_000, max: 4_800_000 },
      local: { min: 1_400_000, max: 2_800_000 },
    },
  },
  {
    id: 'vienna',
    name: '빈',
    nameEn: 'Vienna',
    region: '유럽',
    coordinates: [16.37, 48.21],
    concepts: ['관광', '쇼핑'],
    accommodationTypes: ['호텔'],
    budgetRange: { min: 5_000_000, max: 10_000_000 },
    nights: 6,
    features: ['쇤브룬 궁전', '슈테판 대성당', '카페 문화', '오페라 하우스'],
    bestBookingWeeks: 12,
    visaRequired: false,
    description: '합스부르크 왕가의 궁전과 카페 문화가 살아있는 음악의 도시입니다.',
    markerEmoji: '🎵',
    highlights: ['쇤브룬 궁전 & 정원', '빈 국립 오페라 공연', '카페 자허 자허토르테'],
    costBreakdown: {
      flight: { min: 1_400_000, max: 2_400_000 },
      accommodation: { min: 2_200_000, max: 4_800_000 },
      local: { min: 1_400_000, max: 2_800_000 },
    },
  },
  {
    id: 'budapest',
    name: '부다페스트',
    nameEn: 'Budapest',
    region: '유럽',
    coordinates: [19.04, 47.5],
    concepts: ['관광', '휴양'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 5_000_000, max: 9_000_000 },
    nights: 6,
    features: ['부다 왕궁', '세체니 온천', '다뉴브 야경', '폐허 바'],
    bestBookingWeeks: 10,
    visaRequired: false,
    description: '도나우 강의 진주, 야경과 온천으로 유명한 부다페스트입니다.',
    markerEmoji: '♨️',
    highlights: ['세체니 온천 체험', '다뉴브강 야경 크루즈', '어부의 요새 전망'],
    costBreakdown: {
      flight: { min: 1_400_000, max: 2_300_000 },
      accommodation: { min: 2_000_000, max: 4_000_000 },
      local: { min: 1_600_000, max: 2_700_000 },
    },
  },
  {
    id: 'iceland',
    name: '아이슬란드',
    nameEn: 'Iceland',
    region: '유럽',
    coordinates: [-21.94, 64.15],
    concepts: ['관광', '액티비티'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 7_000_000, max: 15_000_000 },
    nights: 7,
    features: ['오로라', '블루라군', '골든서클', '빙하 하이킹'],
    bestBookingWeeks: 16,
    visaRequired: false,
    description: '오로라와 빙하, 화산이 공존하는 지구 밖 같은 대자연을 경험하세요.',
    markerEmoji: '🌌',
    highlights: ['오로라 헌팅 투어', '블루라군 온천', '요쿨살론 빙하 호수'],
    costBreakdown: {
      flight: { min: 2_000_000, max: 3_500_000 },
      accommodation: { min: 2_500_000, max: 6_000_000 },
      local: { min: 2_500_000, max: 5_500_000 },
    },
  },
  {
    id: 'istanbul',
    name: '이스탄불',
    nameEn: 'Istanbul',
    region: '유럽',
    coordinates: [28.98, 41.01],
    concepts: ['관광', '쇼핑'],
    accommodationTypes: ['호텔'],
    budgetRange: { min: 5_000_000, max: 9_000_000 },
    nights: 6,
    features: ['아야소피아', '그랜드바자르', '보스포루스 크루즈', '터키 음식'],
    bestBookingWeeks: 10,
    visaRequired: false,
    description: '동양과 서양이 만나는 이스탄불에서 두 대륙의 매력을 느끼세요.',
    markerEmoji: '🕌',
    highlights: ['아야소피아 & 블루모스크', '보스포루스 해협 크루즈', '그랜드바자르 쇼핑'],
    costBreakdown: {
      flight: { min: 1_200_000, max: 2_000_000 },
      accommodation: { min: 2_000_000, max: 4_000_000 },
      local: { min: 1_800_000, max: 3_000_000 },
    },
  },
  {
    id: 'mykonos',
    name: '미코노스',
    nameEn: 'Mykonos',
    region: '유럽',
    coordinates: [25.33, 37.45],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 6_000_000, max: 12_000_000 },
    nights: 6,
    features: ['풍차 언덕', '파라다이스 비치', '리틀 베니스', '델로스 섬'],
    bestBookingWeeks: 14,
    visaRequired: false,
    description: '에게해의 보석, 순백의 풍차마을에서 럭셔리 허니문을 즐기세요.',
    markerEmoji: '🌬️',
    highlights: ['카토밀리 풍차 석양', '파라다이스 비치 클럽', '델로스 유적 투어'],
    costBreakdown: {
      flight: { min: 1_500_000, max: 2_500_000 },
      accommodation: { min: 3_000_000, max: 6_500_000 },
      local: { min: 1_500_000, max: 3_000_000 },
    },
  },
  {
    id: 'porto',
    name: '포르투',
    nameEn: 'Porto',
    region: '유럽',
    coordinates: [-8.61, 41.15],
    concepts: ['관광', '쇼핑'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 5_000_000, max: 9_000_000 },
    nights: 6,
    features: ['동 루이스 다리', '포트와인', '아줄레주 타일', '호베이라 지구'],
    bestBookingWeeks: 10,
    visaRequired: false,
    description: '포트와인의 고향, 아줄레주 타일이 아름다운 도루강변 도시입니다.',
    markerEmoji: '🍷',
    highlights: ['동 루이스 다리 일몰', '포트와인 셀러 투어', '렐루 서점 방문'],
    costBreakdown: {
      flight: { min: 1_400_000, max: 2_300_000 },
      accommodation: { min: 2_000_000, max: 4_000_000 },
      local: { min: 1_600_000, max: 2_700_000 },
    },
  },
  {
    id: 'malta',
    name: '몰타',
    nameEn: 'Malta',
    region: '유럽',
    coordinates: [14.51, 35.9],
    concepts: ['관광', '휴양'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 5_000_000, max: 9_500_000 },
    nights: 6,
    features: ['발레타 구시가지', '블루 그로토', '고조 섬', '기사단 역사'],
    bestBookingWeeks: 10,
    visaRequired: false,
    description: '지중해 한가운데 떠 있는 기사단의 섬에서 역사와 바다를 즐기세요.',
    markerEmoji: '⚔️',
    highlights: ['발레타 구시가지 투어', '블루 그로토 보트 투어', '고조 섬 치타델라'],
    costBreakdown: {
      flight: { min: 1_500_000, max: 2_500_000 },
      accommodation: { min: 2_000_000, max: 4_200_000 },
      local: { min: 1_500_000, max: 2_800_000 },
    },
  },
  {
    id: 'cinque-terre',
    name: '친퀘테레',
    nameEn: 'Cinque Terre',
    region: '유럽',
    coordinates: [9.72, 44.13],
    concepts: ['관광', '휴양'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 5_500_000, max: 10_000_000 },
    nights: 5,
    features: ['컬러풀 마을', '해안 트레킹', '페스토 파스타', '보트 투어'],
    bestBookingWeeks: 12,
    visaRequired: false,
    description: '절벽 위 다섯 개의 알록달록한 어촌 마을을 따라 트레킹하세요.',
    markerEmoji: '🏘️',
    highlights: ['5개 마을 해안 트레킹', '마나롤라 포토스팟', '보트 투어로 5개 마을 일주'],
    costBreakdown: {
      flight: { min: 1_400_000, max: 2_400_000 },
      accommodation: { min: 2_300_000, max: 4_800_000 },
      local: { min: 1_800_000, max: 2_800_000 },
    },
  },
  {
    id: 'split',
    name: '스플리트',
    nameEn: 'Split',
    region: '유럽',
    coordinates: [16.44, 43.51],
    concepts: ['관광', '휴양'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 5_000_000, max: 9_000_000 },
    nights: 6,
    features: ['디오클레티안 궁전', '흐바르 섬', '마르얀 힐', '달마시아 음식'],
    bestBookingWeeks: 10,
    visaRequired: false,
    description: '로마 황제의 궁전이 살아있는 아드리아해 해안 도시입니다.',
    markerEmoji: '🏛️',
    highlights: ['디오클레티안 궁전 투어', '흐바르 섬 데이트립', '마르얀 힐 전망대'],
    costBreakdown: {
      flight: { min: 1_400_000, max: 2_300_000 },
      accommodation: { min: 2_000_000, max: 4_000_000 },
      local: { min: 1_600_000, max: 2_700_000 },
    },
  },
  {
    id: 'hallstatt',
    name: '할슈타트',
    nameEn: 'Hallstatt',
    region: '유럽',
    coordinates: [13.65, 47.56],
    concepts: ['관광', '휴양'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 5_500_000, max: 11_000_000 },
    nights: 5,
    features: ['호수 마을', '소금광산', '스카이워크', '알프스 풍경'],
    bestBookingWeeks: 12,
    visaRequired: false,
    description: '동화 속에서 튀어나온 듯한 알프스 호수 마을에서 힐링하세요.',
    markerEmoji: '🏠',
    highlights: ['할슈타트 호수 보트 투어', '소금광산 투어', '5 핑거스 전망대'],
    costBreakdown: {
      flight: { min: 1_500_000, max: 2_500_000 },
      accommodation: { min: 2_300_000, max: 5_500_000 },
      local: { min: 1_700_000, max: 3_000_000 },
    },
  },
  {
    id: 'edinburgh',
    name: '에든버러',
    nameEn: 'Edinburgh',
    region: '유럽',
    coordinates: [-3.19, 55.95],
    concepts: ['관광', '쇼핑'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 5_500_000, max: 10_000_000 },
    nights: 6,
    features: ['에든버러 성', '로열마일', '아서스 시트', '위스키'],
    bestBookingWeeks: 12,
    visaRequired: false,
    description: '해리포터의 영감이 된 중세 고성 도시에서 스코틀랜드를 만나세요.',
    markerEmoji: '🏴',
    highlights: ['에든버러 성 투어', '로열마일 산책', '스카치 위스키 시음'],
    costBreakdown: {
      flight: { min: 1_500_000, max: 2_500_000 },
      accommodation: { min: 2_300_000, max: 4_800_000 },
      local: { min: 1_700_000, max: 2_700_000 },
    },
  },
  {
    id: 'norway',
    name: '노르웨이',
    nameEn: 'Norway',
    region: '유럽',
    coordinates: [7.1, 60.39],
    concepts: ['관광', '액티비티'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 7_000_000, max: 15_000_000 },
    nights: 7,
    features: ['피오르드', '트롤퉁가', '오로라', '스타방에르'],
    bestBookingWeeks: 16,
    visaRequired: false,
    description: '장엄한 피오르드와 오로라가 기다리는 북유럽의 대자연을 경험하세요.',
    markerEmoji: '🦌',
    highlights: ['피오르드 크루즈', '트롤퉁가 하이킹', '프레이케스톨렌 전망대'],
    costBreakdown: {
      flight: { min: 1_800_000, max: 3_000_000 },
      accommodation: { min: 2_700_000, max: 6_000_000 },
      local: { min: 2_500_000, max: 6_000_000 },
    },
  },
  {
    id: 'montenegro',
    name: '몬테네그로',
    nameEn: 'Montenegro',
    region: '유럽',
    coordinates: [18.84, 42.44],
    concepts: ['관광', '휴양'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 5_000_000, max: 9_000_000 },
    nights: 6,
    features: ['코토르 만', '부드바 올드타운', '스벨리 스테판', '아드리아해'],
    bestBookingWeeks: 10,
    visaRequired: false,
    description: '아드리아해의 숨겨진 보석, 코토르 만의 절경을 감상하세요.',
    markerEmoji: '⛵',
    highlights: ['코토르 성벽 트레킹', '부드바 올드타운', '스벨리 스테판 해변'],
    costBreakdown: {
      flight: { min: 1_500_000, max: 2_500_000 },
      accommodation: { min: 2_000_000, max: 4_000_000 },
      local: { min: 1_500_000, max: 2_500_000 },
    },
  },

  // ═══════════════════════════════════════════════════════
  // 북미 (5 total — hawaii 위에 이미 포함, 나머지 4)
  // ═══════════════════════════════════════════════════════
  {
    id: 'new-york',
    name: '뉴욕',
    nameEn: 'New York',
    region: '북미',
    coordinates: [-74.01, 40.71],
    concepts: ['관광', '쇼핑'],
    accommodationTypes: ['호텔'],
    budgetRange: { min: 7_000_000, max: 14_000_000 },
    nights: 7,
    features: ['타임스퀘어', '센트럴파크', '자유의 여신상', '브로드웨이'],
    bestBookingWeeks: 14,
    visaRequired: true,
    description: '세계의 수도 뉴욕에서 브로드웨이와 맨해튼 스카이라인을 즐기세요.',
    markerEmoji: '🗽',
    highlights: ['타임스퀘어 & 브로드웨이 뮤지컬', '센트럴파크 마차 투어', '탑 오브 더 락 야경'],
    costBreakdown: {
      flight: { min: 2_000_000, max: 3_500_000 },
      accommodation: { min: 3_000_000, max: 7_000_000 },
      local: { min: 2_000_000, max: 3_500_000 },
    },
  },
  {
    id: 'los-angeles',
    name: '로스앤젤레스',
    nameEn: 'Los Angeles',
    region: '북미',
    coordinates: [-118.24, 34.05],
    concepts: ['관광', '쇼핑', '액티비티'],
    accommodationTypes: ['호텔'],
    budgetRange: { min: 6_500_000, max: 13_000_000 },
    nights: 7,
    features: ['할리우드', '산타모니카', '유니버설 스튜디오', '게티 센터'],
    bestBookingWeeks: 14,
    visaRequired: true,
    description: '할리우드의 화려함과 캘리포니아 해변의 자유를 동시에 만끽하세요.',
    markerEmoji: '🎬',
    highlights: ['할리우드 명예의 거리', '산타모니카 피어 선셋', '유니버설 스튜디오 투어'],
    costBreakdown: {
      flight: { min: 2_000_000, max: 3_500_000 },
      accommodation: { min: 2_500_000, max: 6_000_000 },
      local: { min: 2_000_000, max: 3_500_000 },
    },
  },
  {
    id: 'miami',
    name: '마이애미',
    nameEn: 'Miami',
    region: '북미',
    coordinates: [-80.19, 25.76],
    concepts: ['휴양', '쇼핑', '액티비티'],
    accommodationTypes: ['호텔', '리조트'],
    budgetRange: { min: 7_000_000, max: 14_000_000 },
    nights: 7,
    features: ['사우스비치', '아르데코 지구', '에버글레이즈', '키웨스트'],
    bestBookingWeeks: 14,
    visaRequired: true,
    description: '형형색색의 아르데코 건물과 카리브해 느낌의 비치에서 힐링하세요.',
    markerEmoji: '🌴',
    highlights: ['사우스비치 선셋 산책', '에버글레이즈 에어보트', '키웨스트 드라이브'],
    costBreakdown: {
      flight: { min: 2_000_000, max: 3_500_000 },
      accommodation: { min: 3_000_000, max: 7_000_000 },
      local: { min: 2_000_000, max: 3_500_000 },
    },
  },
  {
    id: 'vancouver',
    name: '밴쿠버',
    nameEn: 'Vancouver',
    region: '북미',
    coordinates: [-123.12, 49.28],
    concepts: ['관광', '액티비티'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 6_000_000, max: 12_000_000 },
    nights: 7,
    features: ['스탠리파크', '캐필라노 현수교', '그랜빌 아일랜드', '휘슬러'],
    bestBookingWeeks: 12,
    visaRequired: true,
    description: '산과 바다가 어우러진 캐나다 서부의 아름다운 항구 도시입니다.',
    markerEmoji: '🍁',
    highlights: ['스탠리파크 자전거 투어', '캐필라노 현수교', '그랜빌 아일랜드 마켓'],
    costBreakdown: {
      flight: { min: 1_800_000, max: 3_000_000 },
      accommodation: { min: 2_500_000, max: 5_500_000 },
      local: { min: 1_700_000, max: 3_500_000 },
    },
  },

  // ═══════════════════════════════════════════════════════
  // 중남미/카리브 (5 total — cancun 위에 이미 포함, 나머지 4)
  // ═══════════════════════════════════════════════════════
  {
    id: 'cuba',
    name: '쿠바',
    nameEn: 'Cuba',
    region: '중남미/카리브',
    coordinates: [-82.37, 23.11],
    concepts: ['관광', '액티비티'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 6_000_000, max: 11_000_000 },
    nights: 7,
    features: ['클래식카', '올드 하바나', '살사', '바라데로 비치'],
    bestBookingWeeks: 12,
    visaRequired: true,
    description: '시간이 멈춘 듯한 아바나에서 클래식카를 타고 달려보세요.',
    markerEmoji: '🚗',
    highlights: ['올드 하바나 클래식카 투어', '바라데로 비치 휴양', '살사 댄스 레슨'],
    costBreakdown: {
      flight: { min: 2_000_000, max: 3_500_000 },
      accommodation: { min: 2_000_000, max: 4_500_000 },
      local: { min: 2_000_000, max: 3_000_000 },
    },
  },
  {
    id: 'costa-rica',
    name: '코스타리카',
    nameEn: 'Costa Rica',
    region: '중남미/카리브',
    coordinates: [-84.09, 9.93],
    concepts: ['액티비티', '관광'],
    accommodationTypes: ['리조트', '에어비앤비'],
    budgetRange: { min: 7_000_000, max: 13_000_000 },
    nights: 7,
    features: ['아레날 화산', '열대우림 짚라인', '온천', '나무늘보'],
    bestBookingWeeks: 12,
    visaRequired: false,
    description: '열대우림과 화산, 태평양이 만나는 에코 허니문의 성지입니다.',
    markerEmoji: '🦥',
    highlights: ['아레날 화산 온천', '몬테베르데 클라우드 포레스트', '마누엘 안토니오 국립공원'],
    costBreakdown: {
      flight: { min: 2_500_000, max: 4_000_000 },
      accommodation: { min: 2_500_000, max: 5_500_000 },
      local: { min: 2_000_000, max: 3_500_000 },
    },
  },
  {
    id: 'peru',
    name: '페루',
    nameEn: 'Peru',
    region: '중남미/카리브',
    coordinates: [-72.55, -13.16],
    concepts: ['관광', '액티비티'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 7_000_000, max: 14_000_000 },
    nights: 8,
    features: ['마추픽추', '쿠스코', '성스러운 계곡', '세비체'],
    bestBookingWeeks: 14,
    visaRequired: false,
    description: '잉카제국의 잃어버린 도시 마추픽추에서 경이로운 일출을 맞이하세요.',
    markerEmoji: '🦙',
    highlights: ['마추픽추 일출', '쿠스코 잉카 유적 투어', '성스러운 계곡 트레킹'],
    costBreakdown: {
      flight: { min: 2_500_000, max: 4_500_000 },
      accommodation: { min: 2_500_000, max: 5_500_000 },
      local: { min: 2_000_000, max: 4_000_000 },
    },
  },
  {
    id: 'jamaica',
    name: '자메이카',
    nameEn: 'Jamaica',
    region: '중남미/카리브',
    coordinates: [-77.3, 18.11],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['올인클루시브', '리조트'],
    budgetRange: { min: 7_000_000, max: 13_000_000 },
    nights: 7,
    features: ['올인클루시브', '던스리버 폭포', '레게 음악', '블루마운틴 커피'],
    bestBookingWeeks: 12,
    visaRequired: false,
    description: '레게 음악과 카리브해 비치에서 올인클루시브 허니문을 즐기세요.',
    markerEmoji: '🎵',
    highlights: ['올인클루시브 리조트 올데이', '던스리버 폭포 클라이밍', '블루마운틴 커피 투어'],
    costBreakdown: {
      flight: { min: 2_500_000, max: 4_000_000 },
      accommodation: { min: 3_000_000, max: 6_000_000 },
      local: { min: 1_500_000, max: 3_000_000 },
    },
  },

  // ═══════════════════════════════════════════════════════
  // 오세아니아/태평양 (11)
  // ═══════════════════════════════════════════════════════
  {
    id: 'guam',
    name: '괌',
    nameEn: 'Guam',
    region: '오세아니아/태평양',
    coordinates: [144.79, 13.44],
    concepts: ['휴양', '쇼핑', '액티비티'],
    accommodationTypes: ['리조트', '호텔'],
    budgetRange: { min: 3_000_000, max: 6_000_000 },
    nights: 4,
    features: ['투몬 비치', '사랑의 절벽', '면세 쇼핑', '스노클링'],
    bestBookingWeeks: 6,
    visaRequired: true,
    description: '한국에서 4시간, 가까운 미국령 열대 휴양지에서 편하게 쉬세요.',
    markerEmoji: '🌺',
    highlights: ['투몬 비치 선셋', '사랑의 절벽 전망', 'GPO & DFS 면세 쇼핑'],
    costBreakdown: {
      flight: { min: 600_000, max: 1_200_000 },
      accommodation: { min: 1_400_000, max: 3_000_000 },
      local: { min: 1_000_000, max: 1_800_000 },
    },
  },
  {
    id: 'saipan',
    name: '사이판',
    nameEn: 'Saipan',
    region: '오세아니아/태평양',
    coordinates: [145.75, 15.19],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['리조트', '호텔'],
    budgetRange: { min: 3_000_000, max: 6_000_000 },
    nights: 4,
    features: ['마나가하 섬', '그로토', '스카이다이빙', '블루홀 다이빙'],
    bestBookingWeeks: 6,
    visaRequired: false,
    description: '투명한 에메랄드 바다와 모험이 가득한 태평양의 보석입니다.',
    markerEmoji: '🪂',
    highlights: ['마나가하 섬 호핑', '그로토 다이빙', '사이판 스카이다이빙'],
    costBreakdown: {
      flight: { min: 600_000, max: 1_200_000 },
      accommodation: { min: 1_400_000, max: 3_000_000 },
      local: { min: 1_000_000, max: 1_800_000 },
    },
  },
  {
    id: 'fiji',
    name: '피지',
    nameEn: 'Fiji',
    region: '오세아니아/태평양',
    coordinates: [178.07, -17.71],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['리조트', '풀빌라'],
    budgetRange: { min: 7_000_000, max: 14_000_000 },
    nights: 7,
    features: ['프라이빗 아일랜드', '스노클링', '부레 숙소', '전통 카바 의식'],
    bestBookingWeeks: 14,
    visaRequired: false,
    description: '남태평양 333개 섬의 낙원에서 프라이빗 아일랜드 허니문을 즐기세요.',
    markerEmoji: '🏝️',
    highlights: ['프라이빗 아일랜드 리조트', '산호초 스노클링', '전통 카바 세레모니'],
    costBreakdown: {
      flight: { min: 2_000_000, max: 3_500_000 },
      accommodation: { min: 3_500_000, max: 7_500_000 },
      local: { min: 1_500_000, max: 3_000_000 },
    },
  },
  {
    id: 'tahiti',
    name: '타히티',
    nameEn: 'Tahiti',
    region: '오세아니아/태평양',
    coordinates: [-149.43, -17.53],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['풀빌라', '리조트'],
    budgetRange: { min: 8_000_000, max: 15_000_000 },
    nights: 7,
    features: ['수상 방갈로', '모레아 섬', '가오리 스노클링', '흑진주'],
    bestBookingWeeks: 16,
    visaRequired: false,
    description: '프렌치 폴리네시아의 수상 방갈로에서 남태평양의 낭만을 느끼세요.',
    markerEmoji: '🐚',
    highlights: ['수상 방갈로 숙박', '모레아 섬 가오리 투어', '타히티 흑진주 쇼핑'],
    costBreakdown: {
      flight: { min: 2_500_000, max: 4_500_000 },
      accommodation: { min: 4_000_000, max: 8_000_000 },
      local: { min: 1_500_000, max: 2_500_000 },
    },
  },
  {
    id: 'palau',
    name: '팔라우',
    nameEn: 'Palau',
    region: '오세아니아/태평양',
    coordinates: [134.58, 7.51],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['리조트', '호텔'],
    budgetRange: { min: 5_000_000, max: 10_000_000 },
    nights: 5,
    features: ['밀키웨이', '젤리피시 레이크', '록 아일랜드', '다이빙'],
    bestBookingWeeks: 10,
    visaRequired: false,
    description: '세계적인 다이빙 명소, 록 아일랜드의 에메랄드 바다를 탐험하세요.',
    markerEmoji: '🪼',
    highlights: ['밀키웨이 머드팩 체험', '젤리피시 레이크 스노클링', '블루코너 다이빙'],
    costBreakdown: {
      flight: { min: 1_200_000, max: 2_200_000 },
      accommodation: { min: 2_000_000, max: 4_500_000 },
      local: { min: 1_800_000, max: 3_300_000 },
    },
  },
  {
    id: 'sydney',
    name: '시드니',
    nameEn: 'Sydney',
    region: '오세아니아/태평양',
    coordinates: [151.21, -33.87],
    concepts: ['관광', '액티비티'],
    accommodationTypes: ['호텔'],
    budgetRange: { min: 6_000_000, max: 12_000_000 },
    nights: 7,
    features: ['오페라하우스', '하버브릿지', '본다이 비치', '블루마운틴'],
    bestBookingWeeks: 12,
    visaRequired: true,
    description: '세계적인 랜드마크 오페라하우스와 아름다운 항구 도시를 만나세요.',
    markerEmoji: '🎭',
    highlights: ['오페라하우스 공연 관람', '하버브릿지 클라이밍', '블루마운틴 트레킹'],
    costBreakdown: {
      flight: { min: 1_500_000, max: 2_800_000 },
      accommodation: { min: 2_500_000, max: 5_500_000 },
      local: { min: 2_000_000, max: 3_700_000 },
    },
  },
  {
    id: 'gold-coast',
    name: '골드코스트',
    nameEn: 'Gold Coast',
    region: '오세아니아/태평양',
    coordinates: [153.43, -28.0],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['리조트', '호텔'],
    budgetRange: { min: 6_000_000, max: 12_000_000 },
    nights: 7,
    features: ['서퍼스 파라다이스', '테마파크', '래밍턴 국립공원', '서핑'],
    bestBookingWeeks: 12,
    visaRequired: true,
    description: '호주 최고의 해변 도시에서 서핑과 테마파크를 동시에 즐기세요.',
    markerEmoji: '🏄',
    highlights: ['서퍼스 파라다이스 비치', '드림월드 & 무비월드', '래밍턴 반딧불 투어'],
    costBreakdown: {
      flight: { min: 1_500_000, max: 2_800_000 },
      accommodation: { min: 2_500_000, max: 5_500_000 },
      local: { min: 2_000_000, max: 3_700_000 },
    },
  },
  {
    id: 'new-zealand',
    name: '뉴질랜드',
    nameEn: 'New Zealand',
    region: '오세아니아/태평양',
    coordinates: [168.66, -44.99],
    concepts: ['관광', '액티비티'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 7_000_000, max: 13_000_000 },
    nights: 8,
    features: ['밀포드사운드', '반지의 제왕 호빗마을', '번지점프', '별 관측'],
    bestBookingWeeks: 14,
    visaRequired: false,
    description: '반지의 제왕 촬영지, 대자연의 경이로움이 가득한 중간계입니다.',
    markerEmoji: '🧙',
    highlights: ['밀포드사운드 크루즈', '호비튼 무비세트 투어', '퀸스타운 번지점프'],
    costBreakdown: {
      flight: { min: 2_000_000, max: 3_500_000 },
      accommodation: { min: 2_500_000, max: 5_500_000 },
      local: { min: 2_500_000, max: 4_000_000 },
    },
  },
  {
    id: 'cairns',
    name: '케언즈',
    nameEn: 'Cairns',
    region: '오세아니아/태평양',
    coordinates: [145.77, -16.92],
    concepts: ['액티비티', '관광'],
    accommodationTypes: ['리조트', '호텔'],
    budgetRange: { min: 6_000_000, max: 12_000_000 },
    nights: 7,
    features: ['그레이트배리어리프', '데인트리 열대우림', '스카이레일', '쿠란다'],
    bestBookingWeeks: 12,
    visaRequired: true,
    description: '세계 최대 산호초 그레이트배리어리프에서 스노클링 하세요.',
    markerEmoji: '🐠',
    highlights: ['그레이트배리어리프 스노클링', '데인트리 열대우림 투어', '쿠란다 스카이레일'],
    costBreakdown: {
      flight: { min: 1_500_000, max: 2_800_000 },
      accommodation: { min: 2_500_000, max: 5_500_000 },
      local: { min: 2_000_000, max: 3_700_000 },
    },
  },
  {
    id: 'bora-bora',
    name: '보라보라',
    nameEn: 'Bora Bora',
    region: '오세아니아/태평양',
    coordinates: [-151.74, -16.5],
    concepts: ['휴양'],
    accommodationTypes: ['풀빌라', '리조트'],
    budgetRange: { min: 10_000_000, max: 20_000_000 },
    nights: 7,
    features: ['수상 빌라', '오테마누산 전망', '라군 투어', '프라이빗 디너'],
    bestBookingWeeks: 20,
    visaRequired: false,
    description: '지상 최고의 허니문 명소, 보라보라 수상 빌라에서 꿈의 시간을 보내세요.',
    markerEmoji: '💍',
    highlights: ['수상 빌라 프라이빗 디너', '라군 샤크 & 레이 투어', '오테마누산 선셋'],
    costBreakdown: {
      flight: { min: 3_000_000, max: 5_000_000 },
      accommodation: { min: 5_000_000, max: 11_000_000 },
      local: { min: 2_000_000, max: 4_000_000 },
    },
  },
  {
    id: 'whitsundays',
    name: '휘트선데이',
    nameEn: 'Whitsunday Islands',
    region: '오세아니아/태평양',
    coordinates: [148.96, -20.28],
    concepts: ['휴양', '액티비티'],
    accommodationTypes: ['리조트'],
    budgetRange: { min: 7_000_000, max: 13_000_000 },
    nights: 6,
    features: ['화이트헤이븐 비치', '하트 리프', '세일링', '그레이트배리어리프'],
    bestBookingWeeks: 12,
    visaRequired: true,
    description: '하트 모양 산호초와 세계에서 가장 하얀 해변의 세일링 허니문입니다.',
    markerEmoji: '💙',
    highlights: ['화이트헤이븐 비치', '하트 리프 헬기 투어', '요트 세일링'],
    costBreakdown: {
      flight: { min: 1_800_000, max: 3_000_000 },
      accommodation: { min: 3_200_000, max: 6_500_000 },
      local: { min: 2_000_000, max: 3_500_000 },
    },
  },

  // ═══════════════════════════════════════════════════════
  // 중동/아프리카 (7)
  // ═══════════════════════════════════════════════════════
  {
    id: 'dubai',
    name: '두바이',
    nameEn: 'Dubai',
    region: '중동/아프리카',
    coordinates: [55.27, 25.2],
    concepts: ['쇼핑', '관광', '액티비티'],
    accommodationTypes: ['호텔', '리조트'],
    budgetRange: { min: 5_000_000, max: 11_000_000 },
    nights: 6,
    features: ['부르즈 할리파', '두바이 몰', '사막 사파리', '팜 주메이라'],
    bestBookingWeeks: 10,
    visaRequired: false,
    description: '세계에서 가장 높은 빌딩과 럭셔리 쇼핑의 미래 도시입니다.',
    markerEmoji: '🏙️',
    highlights: ['부르즈 할리파 전망대', '두바이 몰 아쿠아리움', '사막 사파리 & BBQ 디너'],
    costBreakdown: {
      flight: { min: 1_200_000, max: 2_200_000 },
      accommodation: { min: 2_000_000, max: 5_000_000 },
      local: { min: 1_800_000, max: 3_800_000 },
    },
  },
  {
    id: 'morocco',
    name: '모로코',
    nameEn: 'Morocco',
    region: '중동/아프리카',
    coordinates: [-7.99, 31.63],
    concepts: ['관광', '액티비티'],
    accommodationTypes: ['리조트', '호텔', '에어비앤비'],
    budgetRange: { min: 5_000_000, max: 10_000_000 },
    nights: 7,
    features: ['사하라 사막', '마라케시 메디나', '블루시티 셰프샤우엔', '리아드 숙소'],
    bestBookingWeeks: 10,
    visaRequired: false,
    description: '사하라 사막의 별밤과 블루시티의 매력에 빠져보세요.',
    markerEmoji: '🐪',
    highlights: ['사하라 사막 낙타 투어 & 글램핑', '셰프샤우엔 블루시티', '마라케시 재마엘프나 광장'],
    costBreakdown: {
      flight: { min: 1_500_000, max: 2_500_000 },
      accommodation: { min: 1_800_000, max: 4_000_000 },
      local: { min: 1_700_000, max: 3_500_000 },
    },
  },
  {
    id: 'zanzibar',
    name: '잔지바르',
    nameEn: 'Zanzibar',
    region: '중동/아프리카',
    coordinates: [39.19, -6.16],
    concepts: ['휴양', '관광'],
    accommodationTypes: ['리조트', '호텔'],
    budgetRange: { min: 6_000_000, max: 11_000_000 },
    nights: 7,
    features: ['스파이스 투어', '스톤타운', '백사장 비치', '돌고래 투어'],
    bestBookingWeeks: 12,
    visaRequired: false,
    description: '향신료의 섬 잔지바르에서 인도양의 청록빛 바다를 만나세요.',
    markerEmoji: '🌿',
    highlights: ['눙위 비치 선셋', '스톤타운 올드시티', '스파이스 농장 투어'],
    costBreakdown: {
      flight: { min: 1_800_000, max: 3_000_000 },
      accommodation: { min: 2_200_000, max: 4_500_000 },
      local: { min: 2_000_000, max: 3_500_000 },
    },
  },
  {
    id: 'cappadocia',
    name: '카파도키아',
    nameEn: 'Cappadocia',
    region: '중동/아프리카',
    coordinates: [34.83, 38.64],
    concepts: ['관광', '액티비티'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 5_000_000, max: 10_000_000 },
    nights: 5,
    features: ['열기구', '동굴 호텔', '괴레메', '지하도시'],
    bestBookingWeeks: 10,
    visaRequired: false,
    description: '수백 개의 열기구가 뜨는 요정 굴뚝의 환상적인 일출을 만나세요.',
    markerEmoji: '🎈',
    highlights: ['열기구 선라이즈 투어', '동굴 호텔 숙박', '괴레메 오픈에어 박물관'],
    costBreakdown: {
      flight: { min: 1_200_000, max: 2_200_000 },
      accommodation: { min: 2_000_000, max: 4_500_000 },
      local: { min: 1_800_000, max: 3_300_000 },
    },
  },
  {
    id: 'cape-town',
    name: '케이프타운',
    nameEn: 'Cape Town',
    region: '중동/아프리카',
    coordinates: [18.42, -33.93],
    concepts: ['관광', '액티비티'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 6_000_000, max: 12_000_000 },
    nights: 7,
    features: ['테이블마운틴', '희망봉', '와인랜드', '볼더스 비치 펭귄'],
    bestBookingWeeks: 12,
    visaRequired: false,
    description: '아프리카 최남단, 테이블마운틴과 희망봉에서 감동적인 여행을 하세요.',
    markerEmoji: '🐧',
    highlights: ['테이블마운틴 케이블카', '희망봉 등대 투어', '스텔렌보스 와이너리 투어'],
    costBreakdown: {
      flight: { min: 2_000_000, max: 3_500_000 },
      accommodation: { min: 2_200_000, max: 5_000_000 },
      local: { min: 1_800_000, max: 3_500_000 },
    },
  },
  {
    id: 'oman',
    name: '오만',
    nameEn: 'Oman',
    region: '중동/아프리카',
    coordinates: [58.39, 23.59],
    concepts: ['관광', '액티비티'],
    accommodationTypes: ['리조트', '호텔'],
    budgetRange: { min: 5_500_000, max: 10_000_000 },
    nights: 6,
    features: ['와히바 사막', '무스캇 그랜드 모스크', '와디 샤브', '피오르드'],
    bestBookingWeeks: 10,
    visaRequired: false,
    description: '아라비안 나이트의 신비로운 사막과 오아시스를 탐험하세요.',
    markerEmoji: '🏜️',
    highlights: ['와히바 사막 글램핑', '와디 샤브 수영', '술탄 카부스 그랜드 모스크'],
    costBreakdown: {
      flight: { min: 1_300_000, max: 2_300_000 },
      accommodation: { min: 2_200_000, max: 4_500_000 },
      local: { min: 2_000_000, max: 3_200_000 },
    },
  },
  {
    id: 'abu-dhabi',
    name: '아부다비',
    nameEn: 'Abu Dhabi',
    region: '중동/아프리카',
    coordinates: [54.37, 24.45],
    concepts: ['관광', '쇼핑', '액티비티'],
    accommodationTypes: ['호텔', '리조트'],
    budgetRange: { min: 5_500_000, max: 11_000_000 },
    nights: 5,
    features: ['셰이크 자이드 모스크', '루브르 아부다비', '야스 아일랜드', '사막 투어'],
    bestBookingWeeks: 10,
    visaRequired: false,
    description: '순백의 대모스크와 루브르 박물관이 있는 중동의 문화 수도입니다.',
    markerEmoji: '🕌',
    highlights: ['셰이크 자이드 그랜드 모스크', '루브르 아부다비 관람', '야스 아일랜드 페라리 월드'],
    costBreakdown: {
      flight: { min: 1_200_000, max: 2_200_000 },
      accommodation: { min: 2_300_000, max: 5_000_000 },
      local: { min: 2_000_000, max: 3_800_000 },
    },
  },

  // ═══════════════════════════════════════════════════════
  // 국내 (6 total — jeju 위에 이미 포함, 나머지 5)
  // ═══════════════════════════════════════════════════════
  {
    id: 'busan',
    name: '부산',
    nameEn: 'Busan',
    region: '국내',
    coordinates: [129.04, 35.1],
    concepts: ['관광', '쇼핑', '액티비티'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 1_000_000, max: 3_000_000 },
    nights: 3,
    features: ['해운대', '광안리', '감천문화마을', '해산물'],
    bestBookingWeeks: 2,
    visaRequired: false,
    description: '바다와 도시가 만나는 부산에서 해운대 선셋과 미식을 즐기세요.',
    markerEmoji: '🌊',
    highlights: ['해운대 해변 산책', '감천문화마을 포토존', '자갈치시장 회 투어'],
    costBreakdown: {
      flight: { min: 100_000, max: 200_000 },
      accommodation: { min: 500_000, max: 1_600_000 },
      local: { min: 400_000, max: 1_200_000 },
    },
  },
  {
    id: 'yeosu',
    name: '여수',
    nameEn: 'Yeosu',
    region: '국내',
    coordinates: [127.66, 34.76],
    concepts: ['휴양', '관광'],
    accommodationTypes: ['호텔', '리조트', '에어비앤비'],
    budgetRange: { min: 1_000_000, max: 3_000_000 },
    nights: 3,
    features: ['여수 밤바다', '향일암', '오동도', '해상케이블카'],
    bestBookingWeeks: 2,
    visaRequired: false,
    description: '여수 밤바다의 로맨틱한 야경 속에서 달콤한 신혼의 밤을 보내세요.',
    markerEmoji: '🌙',
    highlights: ['여수 밤바다 해양공원', '향일암 일출', '해상 케이블카 야경'],
    costBreakdown: {
      flight: { min: 100_000, max: 200_000 },
      accommodation: { min: 500_000, max: 1_600_000 },
      local: { min: 400_000, max: 1_200_000 },
    },
  },
  {
    id: 'gangneung',
    name: '강릉',
    nameEn: 'Gangneung',
    region: '국내',
    coordinates: [128.9, 37.75],
    concepts: ['휴양', '관광'],
    accommodationTypes: ['호텔', '에어비앤비'],
    budgetRange: { min: 1_000_000, max: 3_000_000 },
    nights: 3,
    features: ['경포대', '안목 커피거리', '정동진', '순두부마을'],
    bestBookingWeeks: 2,
    visaRequired: false,
    description: '동해 일출과 커피 한 잔의 여유가 있는 강릉에서 힐링하세요.',
    markerEmoji: '☕',
    highlights: ['정동진 일출', '안목 커피거리 카페투어', '경포대 해변 산책'],
    costBreakdown: {
      flight: { min: 50_000, max: 150_000 },
      accommodation: { min: 500_000, max: 1_600_000 },
      local: { min: 450_000, max: 1_250_000 },
    },
  },
  {
    id: 'sokcho',
    name: '속초',
    nameEn: 'Sokcho',
    region: '국내',
    coordinates: [128.59, 38.21],
    concepts: ['관광', '액티비티'],
    accommodationTypes: ['호텔', '리조트', '에어비앤비'],
    budgetRange: { min: 1_000_000, max: 3_500_000 },
    nights: 3,
    features: ['설악산', '속초 중앙시장', '아바이마을', '청초호'],
    bestBookingWeeks: 2,
    visaRequired: false,
    description: '설악산과 동해가 만나는 속초에서 자연 속 힐링 신혼여행을 즐기세요.',
    markerEmoji: '🏔️',
    highlights: ['설악산 케이블카', '속초 중앙시장 먹방', '영금정 일출'],
    costBreakdown: {
      flight: { min: 50_000, max: 150_000 },
      accommodation: { min: 500_000, max: 1_800_000 },
      local: { min: 450_000, max: 1_550_000 },
    },
  },
  {
    id: 'gyeongju',
    name: '경주',
    nameEn: 'Gyeongju',
    region: '국내',
    coordinates: [129.22, 35.86],
    concepts: ['관광', '휴양'],
    accommodationTypes: ['호텔', '리조트', '에어비앤비'],
    budgetRange: { min: 1_000_000, max: 3_000_000 },
    nights: 3,
    features: ['불국사', '첨성대', '대릉원', '황리단길'],
    bestBookingWeeks: 2,
    visaRequired: false,
    description: '천년 신라의 수도에서 역사와 함께하는 로맨틱 여행을 떠나세요.',
    markerEmoji: '🏛️',
    highlights: ['불국사 & 석굴암', '대릉원 야간 산책', '황리단길 카페 & 한복 체험'],
    costBreakdown: {
      flight: { min: 100_000, max: 200_000 },
      accommodation: { min: 500_000, max: 1_600_000 },
      local: { min: 400_000, max: 1_200_000 },
    },
  },
];
