// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // [CL-OAUTH-LOVABLE-BROKER-20260613-184200] Google OAuth 복귀 시
    // /auth?code=... 를 자동 소비해 세션 수립(정적 호스팅 안전). PKCE = same-origin verifier.
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});